### ISSUE TITLE
Display expected time to complete for users.

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-publish#6]
User should be able to see expected time to complete boosts for the options he has selected.

**Comment by attilaaf** [comment]
As API, provided expected time 
https://github.com/MatterPool/boostpow-api/issues/6
As User, I want to see the Expected time to complete job displayed to user
https://github.com/MatterPool/boostpow-publish/issues/6
As Dev, I want to get a function callback when the expected time is queried, so that I can handle it.
https://github.com/MatterPool/boostpow-publish/issues/22
